routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function(){
	
	Route::middleware('admin')->group(function(){
	    Route::get('dashboard', function () {
		    return view('admin.dashboard');
		})->name('dashboard');
		Route::resource('users', 'UserController');
		Route::get('/plan','PlanController@index')->name('plan.index');
		Route::get('/create/plan','PlanController@create')->name('plan.create');
		Route::post('/edit/plan/{id}','PlanController@edit')->name('plan.edit');
		Route::post('/update/plan','PlanController@update')->name('plan.update');
		Route::delete('/destroy/plan/{id}','PlanController@destroy')->name('plan.destroy');
		Route::post('/users/list','UserController@index')->name('user.index.post');
		Route::post('/users/{id}','UserController@show')->name('users.show.post');
		Route::get('/assign/plan/{id}','UserController@assignPlan')->name('assign.plan');
		Route::post('/assign/plan/{id}','UserController@storeAssignPlan')->name('assign.plan.save');
		Route::post('/store/plan','PlanController@storePlan')->name('plan.store');
		Route::post('/store/feature','PlanController@storeFeature')->name('feature.store');
		Route::post('/store/featureValue','PlanController@storeFeatureValue')->name('featureValue.store');
	});

	Route::namespace('Auth')->group(function(){
        
	    //Login Routes
	    Route::get('/login','LoginController@showLoginForm')->name('login');
	    Route::post('/login','LoginController@login')->name('check.login');
	    Route::post('/logout','LoginController@logout')->name('logout');

	    //Forgot Password Routes
	    Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
	    Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');

	    //Reset Password Routes
	    Route::get('/password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
	    Route::post('/password/reset','ResetPasswordController@reset')->name('password.update');

	});
});


Auth::routes();

Route::middleware('auth')->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/download','UsersDownloadController@store')->name('download');
    Route::get('/all/downloads','UsersDownloadController@index')->name('all.download');
    Route::get('/my-downloads','UsersDownloadController@getByUser')->name('my.download');
    Route::get('/download/{id}','UsersDownloadController@downloadZip')->name('zip.download');
});
Route::redirect('/admin', '/admin/login');

resources/views/admin/assign-plan.blade.php
@extends('admin.layouts.default')
@section('title') {{ __('Assign Plan') }} @endsection
@section('custom-css')
<link href="{{ asset('assets/admin/css/plugins/gijgo.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/admin/css/plugins/sweetalert2.min.css') }}" rel="stylesheet">
@endsection
@section('content')
@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif
    <div class="breadcrumb">
        <h1 class="mr-2">Users</h1>
        <ul>
            <li><a href="{{ route('admin.dashboard')}}">Dashboard</a></li>
            <li><a href="{{ route('admin.users.index')}}">Users</a></li>
            <li>{{ __('Assign Plan') }}</li>
        </ul>
        <span class="flex-grow-1"></span>
    </div>
    <div class="separator-breadcrumb border-top"></div>
    <div class="row">
        <div class="col-md-8">
            <h4>{{ __('Assign Plan') }}</h4>
            <div class="card mb-5">
                <div class="card-body">
                    <form action="{{ route('admin.assign.plan.save', $id) }}" class="needs-validation" method="POST">
                        @csrf
                        @if($subscription)
                        <?php 
                            if ($subscription->isEnded()) {
                                $planStatus = '<span class="badge badge-danger">Inactive</span>';
                            } else {
                                $planStatus = '<span class="badge badge-success">Active</span>';
                            }
                        ?>
                        <div class="form-group row">
                            {!! $planStatus !!}
                        </div>
                        <div class="form-group row">
                            <label for="paln">Plan Name:</label>
                            <label for="paln">{{ $plan }}</label>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3">Plan Expiry Date <strong>{{ date('d M, Y', strtotime($subscription->ends_at)) }}</strong></label>
                        </div>
                        <div class="form-group row">
                            <label for="downloaded">Download Consumed:</label>
                            <label for="downloaded"><strong>{{ $consumed }}</strong></label>
                        </div>
                        <div class="form-group row">
                            <label for="downloaded">Remaining Downloads Available:</label>
                            <label for="downloaded"><strong>{{ $remainings }}</strong></label>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3">Total Downloads in Plan:</label>
                            <label for="inputEmail3"><strong>{{ $total }}</strong></label>
                        </div>
                        @endif
                        <div class="form-group row">
                            <label class="radio radio-primary">
                                <input type="radio" name="plan_state" value="0" @if (!$subscription) checked @endif class="plan_state"><span>New</span><span class="checkmark"></span>
                            </label>
                            <label class="radio radio-primary">
                                <input type="radio" name="plan_state" value="1" @if ($subscription) checked @endif class="plan_state"><span>Renew</span><span class="checkmark"></span>
                            </label>
                            @error('plan_state')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row" id="planSelect">
                            <label for="inputEmail3">Plan</label>
                            <select class="form-control {{ ($errors->has('plan_id')) ?  'is-invalid' : '' }}" name="plan_id" id="plan_id">
                                <option value="">Select</option>
                                @foreach($plans as $plan)
                                    <option value="{{ $plan->id }}" @if ($user->subscription('main') && $user->subscription('main')->plan_id == $plan->id) selected @endif>{{ $plan->name }}</option>
                                @endforeach
                            </select>
                            @error('plan_id')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div id="planContainer" style="display: none">
                            <div class="form-group row">
                                <label for="sort_order">Download value</label>
                                <input class="form-control" id="download_value" type="number" name="download_value" placeholder="Download value" value="{{ old('download_value') }}">
                            </div>
                            <div class="form-group row">
                                <label for="sort_order">Extend By</label>
                                <input class="form-control datepicker {{ ($errors->has('extend_by')) ?  'is-invalid' : '' }}" id="extend_by" type="text" name="extend_by" placeholder="Extend By" value="{{ old('extend_by') }}">
                                @error('extend_by')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button class="btn btn-primary" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- end of main-content -->
@endsection

@section('custom-script')
<script src="{{ asset('assets/admin/js/plugins/gijgo.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function () {
  'use strict'; // Fetch all the forms we want to apply custom Bootstrap validation styles to
    if ($('input[name="plan_state"]:checked').val() == 1) { 
        $('#planSelect').hide();
        //$('#planLabel').html('<label for="inputEmail3">'+$( "#plan_id option:selected" ).text()+'</label>')
        $('#planContainer').show();
    }
    $(document).on('click', '.plan_state', function() {
        if ($(this).val() == 1) {
            $('#planSelect').hide();
            $('#planContainer').show();
        } else {
            $('#planSelect').show();
            $('#planContainer').hide();
        }
    })

    var date = new Date();
    date.setDate(date.getDate()-1);
    $('.datepicker').datepicker({
        uiLibrary: 'bootstrap4',
        minDate:date
    });
});
</script>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Signin | Admin Template</title>
        <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600,700,800,900" rel="stylesheet">
        <link href="{{ asset('assets/admin/css/themes/lite-purple.min.css') }}" rel="stylesheet">
    </head>
    <body>
        <div class="auth-layout-wrap" style="background-image: url({{ asset('assets/admin/images/photo-wide-4.jpg') }})">
            <div class="auth-content">
                <div class="card o-hidden">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="p-4">
                                <div class="auth-logo text-center mb-4"><img src="{{ asset('assets/admin/images/logo.png') }}" alt=""></div>
                                @if (session('error'))
                                    <div class="alert alert-card alert-danger" role="alert">
                                        {{ session('error') }}
                                    </div>
                                @endif
                                <h1 class="mb-3 text-18">Sign In</h1>
                                <form method="POST" action="{{ route('admin.check.login') }}" class="needs-validation">
                                    @csrf
                                    <div class="form-group">
                                        <label for="email">Email address</label>
                                        <input id="email" type="email" class="form-control form-control-rounded @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autofocus>
                                        @error('email')
                                            <span class="invalid-feedback">
                                                {{ $message }}
                                            </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input id="password" type="password" class="form-control form-control-rounded @error('password') is-invalid @enderror" name="password" required>
                                        @error('password')
                                            <span class="invalid-feedback">
                                                {{ $message }}
                                            </span>
                                        @enderror
                                    </div>
                                    <button type="submit" class="btn btn-rounded btn-primary btn-block mt-2">Sign In</button>
                                </form>
                            </div>
                        </div>
                        <div class="col-md-6 text-center" style="background-size: cover;background-image: url({{ asset('assets/admin/images/photo-long-3.jpg') }})">
                            <!-- <div class="pr-3 auth-right"><a class="btn btn-rounded btn-outline-primary btn-outline-email btn-block btn-icon-text" href="signup.html"><i class="i-Mail-with-At-Sign"></i> Sign up with Email</a><a class="btn btn-rounded btn-outline-google btn-block btn-icon-text"><i class="i-Google-Plus"></i> Sign up with Google</a><a class="btn btn-rounded btn-block btn-icon-text btn-outline-facebook"><i class="i-Facebook-2"></i> Sign up with Facebook</a></div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="{{ asset('assets/admin/js/plugins/jquery-3.3.1.min.js') }}"></script>
        <script src="{{ asset('assets/admin/js/plugins/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ asset('assets/admin/js/plugins/perfect-scrollbar.min.js') }}"></script>
        <script src="{{ asset('assets/admin/js/scripts/script.min.js') }}"></script>
        <script src="{{ asset('assets/admin/js/scripts/sidebar.large.script.min.js') }}"></script>
        <script src="{{ asset('assets/admin/js/scripts/form.validation.script.min.js') }}"></script>
    </body>
</html>

resources/views/admin/user-profile.blade.php
@extends('admin.layouts.default')
@section('title') {{ __('Dashboard') }} @endsection
@section('custom-css')
<link href="{{ asset('assets/admin/css/plugins/datatables.min.css') }}" rel="stylesheet">
@endsection
@section('content')
@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif
    <div class="breadcrumb">
        <h1>User Profile</h1>
        <ul>
            <li><a href="{{ route('admin.dashboard')}}">Dashboard</a></li>
            <li><a href="{{ route('admin.users.index')}}">Users</a></li>
            <li>User Profile</li>
        </ul>
    </div>
    <div class="separator-breadcrumb border-top"></div>
    <div class="card user-profile o-hidden mb-4">
        <div class="header-cover" style="background-image: url('{{ asset('assets/admin/images/photo-wide-4.jpg')}}')"></div>
        <div class="user-info"><img class="profile-picture avatar-lg mb-2" src="{{ asset('assets/admin/images/faces/1.jpg') }}" alt="">
            <p class="m-0 text-24">{{ $user->name }}</p>
            <p class="text-muted m-0">Digital Marketer</p>
        </div>
        <div class="card-body">
            <ul class="nav nav-tabs profile-nav mb-4" id="profileTab" role="tablist">
                <!-- <li class="nav-item"><a class="nav-link active" id="timeline-tab" data-toggle="tab" href="#timeline" role="tab" aria-controls="timeline" aria-selected="false">Timeline</a></li> -->
                <li class="nav-item"><a class="nav-link active" id="about-tab" data-toggle="tab" href="#about" role="tab" aria-controls="about" aria-selected="true">About</a></li>
                <li class="nav-item"><a class="nav-link" id="friends-tab" data-toggle="tab" href="#friends" role="tab" aria-controls="friends" aria-selected="false">Downloads</a></li>
            </ul>
            <div class="tab-content" id="profileTabContent">
                <div class="tab-pane fade active show" id="about" role="tabpanel" aria-labelledby="about-tab">
                    <h4>Personal Information</h4>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, commodi quam! Provident quis voluptate asperiores ullam, quidem odio pariatur. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem, nulla eos?
                        Cum non ex voluptate corporis id asperiores doloribus dignissimos blanditiis iusto qui repellendus deleniti aliquam, vel quae eligendi explicabo.
                    </p>
                    <hr>
                    <div class="row">
                        <div class="col-md-4 col-6">
                            <div class="mb-4">
                                <p class="text-primary mb-1"><i class="i-Calendar text-16 mr-1"></i> Birth Date</p><span>1 Jan, 1994</span>
                            </div>
                            <div class="mb-4">
                                <p class="text-primary mb-1"><i class="i-Edit-Map text-16 mr-1"></i> Birth Place</p><span>Dhaka, DB</span>
                            </div>
                            <div class="mb-4">
                                <p class="text-primary mb-1"><i class="i-Globe text-16 mr-1"></i> Lives In</p><span>Dhaka, DB</span>
                            </div>
                        </div>
                        <div class="col-md-4 col-6">
                            <div class="mb-4">
                                <p class="text-primary mb-1"><i class="i-MaleFemale text-16 mr-1"></i> Gender</p><span>1 Jan, 1994</span>
                            </div>
                            <div class="mb-4">
                                <p class="text-primary mb-1"><i class="i-MaleFemale text-16 mr-1"></i> Email</p><span>{{ $user->email}}</span>
                            </div>
                            <div class="mb-4">
                                <p class="text-primary mb-1"><i class="i-Cloud-Weather text-16 mr-1"></i> Website</p><span>www.ui-lib.com</span>
                            </div>
                        </div>
                        <div class="col-md-4 col-6">
                            <div class="mb-4">
                                <p class="text-primary mb-1"><i class="i-Face-Style-4 text-16 mr-1"></i> Profession</p><span>Digital Marketer</span>
                            </div>
                            <div class="mb-4">
                                <p class="text-primary mb-1"><i class="i-Professor text-16 mr-1"></i> Experience</p><span>8 Years</span>
                            </div>
                            <div class="mb-4">
                                <p class="text-primary mb-1"><i class="i-Home1 text-16 mr-1"></i> School</p><span>School of Digital Marketing</span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <h4>Plan Info</h4>
                    <div class="row">
                        <div class="col-md-3 col-6">
                            <div class="p-4 border border-light rounded d-flex align-items-center">
                                <i class="i-Gift-Box text-32 mr-3"></i>
                                <div>
                                    <h4 class="text-18 mb-1">Plan</h4>
                                    <span>{{ $plan }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-6">
                            <div class="p-4 border border-light rounded d-flex align-items-center">
                                <i class="i-Calendar text-32 mr-3"></i>
                                <div>
                                    <h4 class="text-18 mb-1">Expire on</h4>
                                    <span>{{ $endsAt}}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-6">
                            <div class="p-4 border border-light rounded d-flex align-items-center">
                                <i class="i-Data-Download text-32 mr-3"></i>
                                <div>
                                    <h4 class="text-18 mb-1">Downloaded</h4>
                                    <span>{{ 'Total:'. $consumed}}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-6">
                            <div class="p-4 border border-light rounded d-flex align-items-center">
                                <i class="i-Data-Download text-32 mr-3"></i>
                                <div>
                                    <h4 class="text-18 mb-1">Total In Plan</h4>
                                    <span>{{ $remainings}}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <h4>Other Info</h4>
                    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum dolore labore reiciendis ab quo ducimus reprehenderit natus debitis, provident ad iure sed aut animi dolor incidunt voluptatem. Blanditiis, nobis aut.</p>
                    <div class="row">
                        <div class="col-md-2 col-sm-4 col-6 text-center"><i class="i-Plane text-32 text-primary"></i>
                            <p class="text-16 mt-1">Travelling</p>
                        </div>
                        <div class="col-md-2 col-sm-4 col-6 text-center"><i class="i-Camera text-32 text-primary"></i>
                            <p class="text-16 mt-1">Photography</p>
                        </div>
                        <div class="col-md-2 col-sm-4 col-6 text-center"><i class="i-Car-3 text-32 text-primary"></i>
                            <p class="text-16 mt-1">Driving</p>
                        </div>
                        <div class="col-md-2 col-sm-4 col-6 text-center"><i class="i-Gamepad-2 text-32 text-primary"></i>
                            <p class="text-16 mt-1">Gaming</p>
                        </div>
                        <div class="col-md-2 col-sm-4 col-6 text-center"><i class="i-Music-Note-2 text-32 text-primary"></i>
                            <p class="text-16 mt-1">Music</p>
                        </div>
                        <div class="col-md-2 col-sm-4 col-6 text-center"><i class="i-Shopping-Bag text-32 text-primary"></i>
                            <p class="text-16 mt-1">Shopping</p>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="friends" role="tabpanel" aria-labelledby="friends-tab">
                    <div class="row">
                        <div class="card text-left">
                            <div class="card-body">
                                <h4 class="card-title mb-3">Downloads</h4>
                                <p>
                                    The default page control presented by DataTables (forward and backward buttons with up to 7 page numbers in-between) is fine for most situations, but there are cases where you may wish to customise the options presented to
                                    the end user. This is done through DataTables' extensible pagination mechanism, the <a href="//datatables.net/reference/option/pagingType"><code class="option" title="DataTables initialisation option">pagingType</code></a> option.
                                </p>
                                <div class="table-responsive">
                                    <table class="display table table-striped table-bordered" id="downloadTable" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>#Sr.No</th>
                                                <th>Url</th>
                                                <th>No of Pages</th>
                                                <th>Status</th>
                                                <th>Created At</th>
                                                <th>Updated At</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- end of main-content -->
@endsection
@section('custom-script')
<script src="{{ asset('assets/admin/js/plugins/datatables.min.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function(){

      // DataTable
      $('#downloadTable').DataTable({
         processing: true,
         serverSide: true,
         paging:true,
         serverMethod: 'post',
         pagingType: "full_numbers",
         ajax: "{!! route('admin.users.show.post', $user->id) !!}",
         columns: [
            { data: 'DT_RowIndex', name: 'DT_RowIndex'},
            { data: 'url', name: 'url' },
            { data: 'pages', name: 'pages' },
            { data: 'status', name: 'status' },
            { data: 'created_at', name: 'created_at' },
            { data: 'updated_at', name: 'updated_at' },
            { data: 'action', name: 'action', orderable: false, searchable: false }
         ]
      });

    });
</script>
@endsection

resources/views/admin/users.blade.php
@extends('admin.layouts.default')
@section('title') {{ __('Users') }} @endsection
@section('custom-css')
<link href="{{ asset('assets/admin/css/plugins/sweetalert2.min.css') }}" rel="stylesheet">
<link href="{{ asset('assets/admin/css/plugins/datatables.min.css') }}" rel="stylesheet">
@endsection
@section('content')
@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif
@if (session('error'))
    <div class="alert alert-danger" role="alert">
        {{ session('error') }}
    </div>
@endif
    <div class="breadcrumb">
        <h1 class="mr-2">Users</h1>
        <ul>
            <li><a href="{{ route('admin.dashboard')}}">Dashboard</a></li>
            <li>Users</li>
        </ul>
        <span class="flex-grow-1"></span>
        <div class="float-left">
            <a href="{{ route('admin.users.create') }}" class="btn btn-primary btn-block">Add User</a>
        </div>
    </div>
    <div class="separator-breadcrumb border-top"></div>
    <div class="row">
        
        <div class="col-md-12">
            <div class="card text-left">
                <div class="card-body">
                    <h4 class="card-title mb-3">List of all Users </h4>
                   <!--  <p>Responsive tables allow tables to be scrolled horizontally with ease. Make any table responsive across all viewports by wrapping a <code>.table</code> with <code>.table-responsive</code>. Or, pick a maximum breakpoint with
                        which to have a responsive table up to by using <code>.table-responsive{-sm|-md|-lg|-xl}</code>.
                    </p> -->
                    <div class="table-responsive">
                        <table class="display table table-striped table-bordered" id="usersTable">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Email Verified</th>
                                    <th scope="col">Plan</th>
                                    <th scope="col">Plan Ends At</th>
                                    <th scope="col">Plan Status</th>
                                    <th scope="col">Created At</th>
                                    <th scope="col">Updated At</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end of main-content -->
@endsection

@section('custom-script')
<script src="{{ asset('assets/admin/js/plugins/sweetalert2.min.js') }}"></script>
<script src="{{ asset('assets/admin/js/plugins/datatables.min.js') }}"></script>
<script type="text/javascript">

    $(document).ready(function () {
      $(document).on('click', '.delete', function () {
        var id = $(this).data('id');
        swal({
          title: 'Are you sure?',
          text: "You won't be able to revert this!",
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#0CC27E',
          cancelButtonColor: '#FF586B',
          confirmButtonText: 'Yes, delete it!',
          cancelButtonText: 'No, cancel!',
          confirmButtonClass: 'btn btn-success mr-5',
          cancelButtonClass: 'btn btn-danger',
          buttonsStyling: false
        }).then(function () {
            event.preventDefault();
            $('#delete-form-'+id).submit();
        });
      });

      // DataTable
      $('#usersTable').DataTable({
         processing: true,
         serverSide: true,
         paging:true,
         serverMethod: 'post',
         pagingType: "full_numbers",
         ajax: "{!! route('admin.user.index.post', $user->id) !!}",
         columns: [
            { data: 'DT_RowIndex', name: 'DT_RowIndex'},
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            { data: 'email_verified_at', name: 'email_verified_at' },
            { data: 'plan', name: 'plan' },
            { data: 'plan_ends_at', name: 'plan_ends_at' },
            { data: 'plan_status', name: 'plan_status' },
            { data: 'created_at', name: 'created_at' },
            { data: 'updated_at', name: 'updated_at' },
            { data: 'action', name: 'action', orderable: false, searchable: false }
         ]
      });
    });
</script>
@endsection