routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function(){
	
	Route::middleware('admin')->group(function(){
	    Route::get('dashboard', function () {
		    return view('admin.dashboard');
		})->name('dashboard');
		Route::resource('users', 'UserController');
		Route::get('/plan','PlanController@index')->name('plan.index');
		Route::get('/create/plan','PlanController@create')->name('plan.create');
		Route::post('/edit/plan/{id}','PlanController@edit')->name('plan.edit');
		Route::post('/update/plan','PlanController@update')->name('plan.update');
		Route::delete('/destroy/plan/{id}','PlanController@destroy')->name('plan.destroy');
		Route::post('/users/list','UserController@index')->name('user.index.post');
		Route::post('/users/{id}','UserController@show')->name('users.show.post');
		Route::get('/assign/plan/{id}','UserController@assignPlan')->name('assign.plan');
		Route::post('/assign/plan/{id}','UserController@storeAssignPlan')->name('assign.plan.save');
		Route::post('/store/plan','PlanController@storePlan')->name('plan.store');
		Route::post('/store/feature','PlanController@storeFeature')->name('feature.store');
		Route::post('/store/featureValue','PlanController@storeFeatureValue')->name('featureValue.store');
	});

	Route::namespace('Auth')->group(function(){
        
	    //Login Routes
	    Route::get('/login','LoginController@showLoginForm')->name('login');
	    Route::post('/login','LoginController@login')->name('check.login');
	    Route::post('/logout','LoginController@logout')->name('logout');

	    //Forgot Password Routes
	    Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
	    Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');

	    //Reset Password Routes
	    Route::get('/password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
	    Route::post('/password/reset','ResetPasswordController@reset')->name('password.update');

	});
});


Auth::routes();

Route::middleware('auth')->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/download','UsersDownloadController@store')->name('download');
    Route::get('/all/downloads','UsersDownloadController@index')->name('all.download');
    Route::get('/my-downloads','UsersDownloadController@getByUser')->name('my.download');
    Route::get('/download/{id}','UsersDownloadController@downloadZip')->name('zip.download');
});
Route::redirect('/admin', '/admin/login');

app/Models/Plan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Lang;
use App\Custom\Period;
use App\Models\Concerns\HasCode;
use App\Models\Concerns\Resettable;

/**
 * Class Plan
 * @package App\Models
 * @property int $id
 * @property string $name
 * @property string $description
 * @property float $price
 * @property string $interval_unit
 * @property int $interval_count
 * @property int $trial_period_days
 * @property int $sort_order
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 */
class Plan extends Model
{
    use Resettable, HasCode;

    const PLAN_FREE = 'free';
    const PLAN_PREMIUM = 'premium';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'code',
        'description',
        'price',
        'interval_unit',
        'interval_count',
        'trial_period_days',
        'sort_order',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
    ];

    /**
     * Boot function for using with User Events.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        // Default interval is 1 month
        static::saving(function ($model) {
            if (!$model->interval_unit) {
                $model->interval_unit = 'month';
            }

            if (!$model->interval_count) {
                $model->interval_count = 1;
            }
        });
    }

    /**
     * Plan constructor.
     *
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setTable('plans');
    }

    /**
     * Get plan features.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function features()
    {
        return $this
            ->belongsToMany(
                'App\Models\Feature',
                'App\Models\PlanFeature',
                'plan_id',
                'feature_id'
            )
            ->using('App\Models\PlanFeature')
            ->withPivot(['id', 'value', 'note'])
            ->orderBy('sort_order');
    }

    /**
     * Get plan subscriptions.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function subscriptions()
    {
        return $this->hasMany(
            'App\Models\PlanSubscription',
            'plan_id',
            'id'
        );
    }

    /**
     * Check if plan is free.
     *
     * @return bool
     */
    public function isFree(): bool
    {
        return ((float)$this->price <= 0.00);
    }

    /**
     * Check if plan has trial.
     *
     * @return bool
     */
    public function hasTrial(): bool
    {
        return (is_numeric($this->trial_period_days) and $this->trial_period_days > 0);
    }
}

app/Http/Controllers/Admin/PlanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Requests\PlanRequest;
use App\Http\Requests\FeatureRequest;
use App\Http\Requests\FeatureValueRequest;
use App\Models\Plan;
use App\Models\Feature;
use App\Models\PlanFeature;
use Session;

class PlanController extends Controller
{

	public function index()
    {
    	$plans = Plan::all()->sortBy('sort_order');
    	return view('admin.plan.list', compact('plans'));
    }

    public function create(Request $request)
    {
    	$plans = Plan::all();
    	$features = Feature::all();
    	return view('admin.plan.create', compact('plans', 'features'));
    }

    public function edit($id)
    {
    	//$planFeature = PlanFeature::where('id', $id)->first();
    	$plan = Plan::where('id', $id)->first();
    	//$feature = Feature::where('id', $planFeature->feature_id)->first();
    	return view('admin.plan.edit', compact('plan'));
    }

    public function storePlan(PlanRequest $request)
    {
    	$input = $request->all();
    	$plan = Plan::create([
		    'name' => $input['name'],
		    'code' => strtolower(str_replace(' ', '-', $input['name'])),
		    'description' => $input['description'],
		    'price' => $input['price'],
		    'interval_unit' => $input['interval_unit'],
		    'interval_count' => 1,
		    'sort_order' => $input['sort_order'],
		]);
		return redirect()->route('admin.plan.create')->with('status', 'Plan added successfully!');
    }

    public function destroy($id)
    {
    	try {
            if (Plan::destroy($id)) {
                return redirect()->route('admin.plan.index')->with('status', 'Plan has been deleted');
            }
            return redirect()->route('admin.plan.index')->with('error', 'Something went wrong.');
        } catch(Exception $e) {
            return redirect()->route('admin.plan.index')->with('error', $e->getMessage());
        }
    }

    public function storeFeature(FeatureRequest $request)
    {
    	$input = $request->all();
    	$plan = Feature::create([
		    'name' => $input['name'],
		    'code' => strtolower(str_replace(' ', '-', $input['name'])),
		    'description' => $input['description'],
		    'interval_unit' => $input['interval_unit'],
		    'interval_count' => 1,
		    'sort_order' => $input['sort_order'],
		]);
		return redirect()->route('admin.plan.create')->with('status', 'Feature added successfully!');
    }

    public function storeFeatureValue(FeatureValueRequest $request)
    {
    	$input = $request->all();
    	$plan = Plan::where('id', $input['plan_id'])->first();
    	$feature = Feature::where('id', $input['feature_id'])->first();
		$plan->features()->attach([
		    $feature->id => [
		    	'value' => $input['value'],
		    	'note' => $input['note']
			]
		]);
		return redirect()->route('admin.plan.create')->with('status', 'Feature value added successfully!');
    }

    public function update(Request $request)
    {
    	$input = $request->all();
    	$fields['plan_id'] = $input['plan_id'];    
    	$fields['plan_id'] = 'required';
    	$fields['price'] = $input['price'];    
    	$fields['price'] = 'required';    
		$rules['plan_name'] = $input['plan_name'];
		$rules['plan_name'] = 'required|unique:plans,name,'.$input['plan_id'];
    	foreach ($input['feature_id'] as $key => $value) {
			$fields['feature_id.'.$key] = $value;    
			$rules['feature_id.'.$key] = 'required';
		}
		foreach ($input['feature_name'] as $key => $value) {
			$fields['feature_name.'.$key] = $value;    
			$rules['feature_name.'.$key] = 'required|unique:features,name,'.$input['feature_id'][$key];
		}
		foreach ($input['value'] as $key => $value) {
			$fields['value.'.$key] = $value;    
			$rules['value'] = [
	           	'required',
	           	Rule::unique('plan_features')
	           	->where('plan_id', $input['plan_id'])
	           	->where('feature_id', $input['feature_id'][$key])
	           	->ignore($input['id'][$key], 'id')
            ];
		}
		foreach ($input['note'] as $key => $value) {
			$fields['note.'.$key] = $value;    
			$rules['note.'.$key] = 'required';
		}
		
    	$this->validate($request, $rules);
	    if ($validator) {
			return response()->json(['error'=>$validator->errors()->all()]);
        }
        $plan = Plan::findOrFail($input['plan_id']);
        $plan->name = $input['plan_name'];
        $plan->price = $input['price'];
        $plan->interval_unit = $input['interval_unit'];
        $plan->sort_order = $input['sort_order'];
        $plan->save();
        foreach ($input['feature_id'] as $key => $value) {
        	$feature = Feature::findOrFail($value);
	        $feature->name = $input['feature_name'][$key];
	        $feature->interval_unit = $input['feture_interval_unit'][$key];
        	$feature->sort_order = $input['feture_sort_order'][$key];
	        $feature->save();
        }
        foreach ($input['id'] as $key => $value) {
        	$planFeature = PlanFeature::findOrFail($value);
	        $planFeature->value = $input['value'][$key];
	        $planFeature->note = $input['note'][$key];
	        $planFeature->save();
        }
        Session::flash('status', $input['plan_name'].' plan updated successfully');
		return response()->json(['status' => 'success']);	
    }

}

resources/views/admin/plan/create.blade.php
@extends('admin.layouts.default')
@section('title') {{ __('Users') }} @endsection
@section('custom-css')
<link href="{{ asset('assets/admin/css/plugins/sweetalert2.min.css') }}" rel="stylesheet">
@endsection
@section('content')
@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif
@if ($plan)
<?php $title = 'Edit Plan';?>
<?php $route = route('admin.users.update', $plan->id);?>
@else
<?php $title = 'Add Plan';?>
<?php $route = route('admin.users.store');?>
@endif
    <div class="breadcrumb">
        <h1 class="mr-2">Users</h1>
        <ul>
            <li><a href="{{ route('admin.dashboard')}}">Dashboard</a></li>
            <li><a href="{{ route('admin.plan.index')}}">Plan</a></li>
            <li>{{ $title }}</li>
        </ul>
        <span class="flex-grow-1"></span>
    </div>
    <div class="separator-breadcrumb border-top"></div>
    <div class="row">
        <div class="col-md-4">
            <h4>{{ $title }}</h4>
            <p>A form control layout using row with left label alignment.</p>
            <div class="card mb-3">
                <div class="card-body">
                    <form action="{{ route('admin.plan.store')}}" class="needs-validation" method="POST">
                        @csrf
                        <div class="form-group row">
                            <label for="name">Name</label>
                            <input class="form-control {{ ($errors->has('name') ?  'is-invalid' : '') }}" id="name" type="text" name="name" placeholder="Name" value="{{ old('name')}}" required="required">
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3">Description</label>
                            <textarea class="form-control {{ ($errors->has('email')) ?  'is-invalid' : '' }}" name="description" id="description" placeholder="Description" required>{{ old('description') }}</textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3">Price</label>
                            <input class="form-control {{ ($errors->has('price')) ?  'is-invalid' : '' }}" name="price" id="price" type="text" placeholder="Price" required>
                            @error('price')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <label for="interval_unit">Interval</label>
                            <select class="form-control {{ ($errors->has('interval_unit')) ?  'is-invalid' : '' }}" name="interval_unit" id="interval_unit">
                                <option value="">Select</option> 
                                <option value="month">Month</option> 
                                <option value="year">Year</option> 
                            </select>
                            @error('interval_unit')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <label for="sort_order">Sort Order</label>
                            <input class="form-control {{ ($errors->has('sort_order')) ?  'is-invalid' : '' }}" id="sort_order" type="number" name="sort_order" placeholder="Sort Order" value="{{ old('sort_order') }}" required="required">
                            @error('sort_order')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button class="btn btn-primary" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <h4>Add Feature</h4>
            <p>A form control layout using row with left label alignment.</p>
            <div class="card mb-3">
                <div class="card-body">
                    <form action="{{ route('admin.feature.store')}}" class="needs-validation" method="POST">
                        @csrf
                        <div class="form-group row">
                            <label for="name">Name</label>
                            <input class="form-control {{ ($errors->has('name')) ?  'is-invalid' : '' }}" id="name" type="text" name="name" placeholder="Name" value="{{ old('name') }}" required="required">
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3">Description</label>
                            <textarea class="form-control {{ ($errors->has('email')) ?  'is-invalid' : '' }}" name="description" id="description" placeholder="Description" required>{{ old('description', $plan->description) }}</textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="interval_unit">Interval</label>
                            <select class="form-control {{ ($errors->has('interval_unit')) ?  'is-invalid' : '' }}" name="interval_unit" id="interval_unit">
                                <option value="">Select</option> 
                                <option value="day">Day</option> 
                                <option value="week">Week</option> 
                                <option value="month">Month</option> 
                                <option value="year">Year</option> 
                            </select>
                            @error('interval_unit')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="sort_order">Sort Order</label>
                            <input class="form-control {{ ($errors->has('sort_order')) ?  'is-invalid' : '' }}" id="sort_order" type="number" name="sort_order" placeholder="Sort Order" value="{{ old('sort_order') }}" required="required">
                            @error('sort_order')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button class="btn btn-primary" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <h4>Add Features Value</h4>
            <p>A form control layout using row with left label alignment.</p>
            <div class="card mb-3">
                <div class="card-body">
                    <form action="{{ route('admin.featureValue.store')}}" class="needs-validation" method="POST">
                        @csrf
                        <div class="form-group row">
                            <label for="inputEmail3">Plan</label>
                            <select class="form-control {{ ($errors->has('plan_id')) ?  'is-invalid' : '' }}" name="plan_id" id="plan_id">
                            <option value="">Select</option> 
                            @foreach($plans as $plan)
                                <option value="{{ $plan->id }}">{{ $plan->name }}</option>
                            @endforeach
                            </select>
                            @error('plan_id')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3">Feature</label>
                            <select class="form-control {{ ($errors->has('feature_id')) ?  'is-invalid' : '' }}" name="feature_id" id="feature_id">
                                <option value="">Select</option> 
                                @foreach($features as $feature)
                                    <option value="{{ $feature->id }}">{{ $feature->name }}</option>
                                @endforeach
                            </select>
                            @error('feature_id')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3">Value</label>
                            <input class="form-control {{ ($errors->has('value')) ?  'is-invalid' : '' }}" name="value" id="value" type="text" placeholder="Value" required>
                            @error('value')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3">Note</label>
                            <textarea class="form-control {{ ($errors->has('note')) ?  'is-invalid' : '' }}" name="note" id="note" placeholder="Note" required>{{ old('note') }}</textarea>
                            @error('note')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button class="btn btn-primary" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- end of main-content -->
@endsection

@section('custom-script')
<script src="{{ asset('assets/admin/js/plugins/sweetalert2.min.js') }}"></script>
<script type="text/javascript">
$(document).ready(function () {
  $(document).on('click', '#addRow', function () {
      $("#firstRow").clone().appendTo("featureForm");
  });
});
</script>
@endsection

resources/views/admin/plan/list.blade.php
@extends('admin.layouts.default')
@section('title') {{ __('Plans') }} @endsection
@section('custom-css')
<link href="{{ asset('assets/admin/css/plugins/sweetalert2.min.css') }}" rel="stylesheet">
@endsection
@section('content')
@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif
<?php 
$colors = [
    0 => 'indigo-400',
    1 => 'pink-400',
    2 => 'teal-400',
    3 => 'cyan-400',
    4 => '',
    5 => '',
];
?>
<div class="breadcrumb">
    <h1 class="mr-2">Plans</h1>
    <ul>
        <li><a href="{{ route('admin.dashboard')}}">Dashboard</a></li>
        <li>Plans</li>
    </ul>
    <span class="flex-grow-1"></span>
    <div class="float-left">
        <a href="{{ route('admin.plan.create') }}" class="btn btn-primary btn-block">Add Plan</a>
    </div>
</div>
<div class="separator-breadcrumb border-top"></div>
<!-- <div class="row">
    <?php //echo '<pre>'.print_r($users, true).'</pre>';?>
    <div class="col-md-12">
        <div class="card text-left">
            <div class="card-body">
                <h4 class="card-title mb-3">List of all Plans </h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Code</th>
                                <th scope="col">Description</th>
                                <th scope="col">Price</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Updated At</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($plans as $plan)
                            <tr>
                                <th scope="row">{{ $plan->id }}</th>
                                <td>{{ $plan->name }}</td>
                                <td>{{ $plan->code }}</td>
                                <td>{{ $plan->description }}</td>
                                <td>{{ $plan->price }}</td>
                                <td>{{ $plan->created_at }}</td>
                                <td>{{ $plan->updated_at }}</td>
                                <td>
                                    <a class="text-success mr-2" href="{{ route('admin.plan.edit', $plan->id) }}">
                                        <i class="nav-icon i-Pen-2 font-weight-bold"></i>
                                    </a>
                                    <a class="text-danger delete mr-2" href="#" data-id="{{ $plan->id }}">
                                        <i class="nav-icon i-File-Trash font-weight-bold"></i>
                                    </a>
                                    <form id="delete-form-{{ $plan->id }}" action="{{ route('admin.plan.destroy', $plan->id) }}" method="POST" style="display: none;">
                                        @method('delete')
                                        @csrf
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div> -->
<section>
    <div class="row mb-4 mt-4">
        @foreach($plans as $key => $plan)
        <?php //var_dump($plan->features()->get());?>
        <div class="col-lg-4 col-md-4 mb-4 text-center">
            <div class="card o-hidden mb-4">
                <div class="mb-4 card-header {{ $colors[$key]}}">
                    <div class="card-title text-white">{{ $plan->name }}</div>
                    <h4 class="text-white">{{ $plan->price }}</h4>
                </div>
                <div class="ul-widget-app__browser-list">
                    @foreach($plan->features()->get() as $feature)
                        <?php //var_dump($feature->pivot);?>
                        <div class="ul-widget-app__browser-list-1 mb-4">
                            <span class="text-15 ml-4">{{ $feature->name }}</span>
                            <span class="badge badge-round-success pill mr-2">{{ $feature->pivot->value }}</span>
                        </div>
                    @endforeach
                </div>
                <a href="javascript:;" class="btn btn-default plan-modal" data-id="{{ $plan->id }}">Edit</a>&nbsp;
                <a class="text-danger delete" href="#" data-id="{{ $plan->id }}">
                    Delete
                </a>
                <form id="delete-form-{{ $plan->id }}" action="{{ route('admin.plan.destroy', $plan->id) }}" method="POST" style="display: none;">
                    @method('delete')
                    @csrf
                </form>
            </div>
        </div>
        @endforeach
    </div>
    <div id="modalContainer"></div>
</section>
<!-- end of main-content -->
@endsection

@section('custom-script')
<script src="{{ asset('assets/admin/js/plugins/sweetalert2.min.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.delete').on('click', function () {
            var id = $(this).data('id');
            swal({
              title: 'Are you sure?',
              text: "You won't be able to revert this!",
              type: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#0CC27E',
              cancelButtonColor: '#FF586B',
              confirmButtonText: 'Yes, delete it!',
              cancelButtonText: 'No, cancel!',
              confirmButtonClass: 'btn btn-success mr-5',
              cancelButtonClass: 'btn btn-danger',
              buttonsStyling: false
            }).then(function () {
                event.preventDefault();
                $('#delete-form-'+id).submit();
            });
        });

        $(document).on('click','.plan-modal',function(){
           var id = $(this).data('id');
           $.ajax({
                type:'post',
                url:'/admin/edit/plan/'+id,
                dataType:'html',
                success:function(data) {
                  $("#modalContainer").html(data);
                  $("#planModal").modal("show");
                }
            });
             
        });

        $(document).on('click', '#planSubmit', function(event) {
            event.preventDefault();
            var formData = $('#planForm').serialize();
            var url = "{{ route('admin.plan.update')}}";
           // alert(url+"\n"+formData);
            $.ajax({
                method: 'POST',
                url: url,
                dataType: 'json',
                data: formData,
                success: function(msg) {
                    console.log(msg)
                  var value = eval(msg);
                  if(value.status == 'success'){
                    window.location.href = "{{ route('admin.plan.index')}}";
                    return false;
                  }
                },
                error: function(response) {
                    $.each(response.responseJSON.errors, function(index, value) {
                        console.log(index+"---"+value)
                        console.log("#" +index+'_error');
                        $('#' +index+'_error').html(value);
                        $('#feature_name.1_error').html(value)
                        alert($('#' +index+'_error').text())
                    });
                     //$('#feature_name.1_error').text(response.responseJSON.errors.feature_name);
               //      $('#emailError').text(response.responseJSON.errors.email);
               //      $('#mobileNumberError').text(response.responseJSON.errors.mobile_number);
               //      $('#aboutError').text(response.responseJSON.errors.about);
               }

            });
        });
    });
</script>
@endsection