routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Route::prefix('/admin')->name('admin.')->namespace('Admin')->group(function(){
	
	Route::middleware('admin')->group(function(){
	    Route::get('dashboard', function () {
		    return view('admin.dashboard');
		})->name('dashboard');
		Route::resource('users', 'UserController');
		Route::get('/plan','PlanController@index')->name('plan.index');
		Route::get('/create/plan','PlanController@create')->name('plan.create');
		Route::post('/edit/plan/{id}','PlanController@edit')->name('plan.edit');
		Route::post('/update/plan','PlanController@update')->name('plan.update');
		Route::delete('/destroy/plan/{id}','PlanController@destroy')->name('plan.destroy');
		Route::post('/users/list','UserController@index')->name('user.index.post');
		Route::post('/users/{id}','UserController@show')->name('users.show.post');
		Route::get('/assign/plan/{id}','UserController@assignPlan')->name('assign.plan');
		Route::post('/assign/plan/{id}','UserController@storeAssignPlan')->name('assign.plan.save');
		Route::post('/store/plan','PlanController@storePlan')->name('plan.store');
		Route::post('/store/feature','PlanController@storeFeature')->name('feature.store');
		Route::post('/store/featureValue','PlanController@storeFeatureValue')->name('featureValue.store');
	});

	Route::namespace('Auth')->group(function(){
        
	    //Login Routes
	    Route::get('/login','LoginController@showLoginForm')->name('login');
	    Route::post('/login','LoginController@login')->name('check.login');
	    Route::post('/logout','LoginController@logout')->name('logout');

	    //Forgot Password Routes
	    Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
	    Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');

	    //Reset Password Routes
	    Route::get('/password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
	    Route::post('/password/reset','ResetPasswordController@reset')->name('password.update');

	});
});


Auth::routes();

Route::middleware('auth')->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/download','UsersDownloadController@store')->name('download');
    Route::get('/all/downloads','UsersDownloadController@index')->name('all.download');
    Route::get('/my-downloads','UsersDownloadController@getByUser')->name('my.download');
    Route::get('/download/{id}','UsersDownloadController@downloadZip')->name('zip.download');
});
Route::redirect('/admin', '/admin/login');

resources/views/admin/includes/footer.blade.php
<div class="flex-grow-1"></div>
<div class="app-footer">
    <!-- <div class="row">
        <div class="col-md-9">
            <p><strong>Gull - Laravel + Bootstrap 4 admin template</strong></p>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero quis beatae officia saepe perferendis voluptatum minima eveniet voluptates dolorum, temporibus nisi maxime nesciunt totam repudiandae commodi sequi dolor quibusdam
                <sunt></sunt>
            </p>
        </div>
    </div> -->
    <div class="footer-bottom d-flex flex-column flex-sm-row align-items-center">
        <!-- <a class="btn btn-primary text-white btn-rounded" href="https://themeforest.net/item/gull-bootstrap-laravel-admin-dashboard-template/23101970" target="_blank">Buy Gull HTML</a> -->
        <span class="flex-grow-1"></span>
        <div class="d-flex align-items-center">
            <img class="logo" src="{{ asset('assets/admin/images/logo.png') }}" alt="">
            <div>
                <p class="m-0">&copy; 2018 Gull HTML</p>
                <p class="m-0">All rights reserved</p>
            </div>
        </div>
    </div>
</div>

resources/views/admin/includes/head.blade.php
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="csrf-token" content="{{ csrf_token() }}" />
<title>Blank | Gull Admin Template</title>
<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600,700,800,900" rel="stylesheet">
<link href="{{ asset('assets/admin/css/themes/lite-purple.min.css') }}" rel="stylesheet">
<link href="{{ asset('assets/admin/css/plugins/perfect-scrollbar.min.css') }}" rel="stylesheet">

resources/views/admin/includes/header.blade.php
<div class="main-header">
    <div class="logo">
        <img src="{{ asset('assets/admin/images/logo.png') }}" alt="">
    </div>
    <div class="menu-toggle">
        <div></div>
        <div></div>
        <div></div>
    </div>
    <div style="margin: auto"></div>
    <div class="header-part-right">
        <!-- Full screen toggle -->
        <i class="i-Full-Screen header-icon d-none d-sm-inline-block" data-fullscreen></i>
        <!-- Grid menu Dropdown -->
        <div class="dropdown">
            <i class="i-Safe-Box text-muted header-icon" role="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <div class="menu-icon-grid">
                    <a href="#"><i class="i-Shop-4"></i> Home</a>
                    <a href="#"><i class="i-Library"></i> UI Kits</a>
                    <a href="#"><i class="i-Drop"></i> Apps</a>
                    <a href="#"><i class="i-File-Clipboard-File--Text"></i> Forms</a>
                    <a href="#"><i class="i-Checked-User"></i> Sessions</a>
                    <a href="#"><i class="i-Ambulance"></i> Support</a>
                </div>
            </div>
        </div>
        <!-- Notificaiton -->
        <div class="dropdown">
            <div class="badge-top-container" role="button" id="dropdownNotification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="badge badge-primary">3</span>
                <i class="i-Bell text-muted header-icon"></i>
            </div>
            <!-- Notification dropdown -->
            <div class="dropdown-menu dropdown-menu-right notification-dropdown rtl-ps-none" aria-labelledby="dropdownNotification" data-perfect-scrollbar data-suppress-scroll-x="true">
                <div class="dropdown-item d-flex">
                    <div class="notification-icon">
                        <i class="i-Speach-Bubble-6 text-primary mr-1"></i>
                    </div>
                    <div class="notification-details flex-grow-1">
                        <p class="m-0 d-flex align-items-center">
                            <span>New message</span>
                            <span class="badge badge-pill badge-primary ml-1 mr-1">new</span>
                            <span class="flex-grow-1"></span>
                            <span class="text-small text-muted ml-auto">10 sec ago</span>
                        </p>
                        <p class="text-small text-muted m-0">James: Hey! are you busy?</p>
                    </div>
                </div>
                <div class="dropdown-item d-flex">
                    <div class="notification-icon">
                        <i class="i-Receipt-3 text-success mr-1"></i>
                    </div>
                    <div class="notification-details flex-grow-1">
                        <p class="m-0 d-flex align-items-center">
                            <span>New order received</span>
                            <span class="badge badge-pill badge-success ml-1 mr-1">new</span>
                            <span class="flex-grow-1"></span>
                            <span class="text-small text-muted ml-auto">2 hours ago</span>
                        </p>
                        <p class="text-small text-muted m-0">1 Headphone, 3 iPhone x</p>
                    </div>
                </div>
                <div class="dropdown-item d-flex">
                    <div class="notification-icon">
                        <i class="i-Empty-Box text-danger mr-1"></i>
                    </div>
                    <div class="notification-details flex-grow-1">
                        <p class="m-0 d-flex align-items-center">
                            <span>Product out of stock</span>
                            <span class="badge badge-pill badge-danger ml-1 mr-1">3</span>
                            <span class="flex-grow-1"></span>
                            <span class="text-small text-muted ml-auto">10 hours ago</span>
                        </p>
                        <p class="text-small text-muted m-0">Headphone E67, R98, XL90, Q77</p>
                    </div>
                </div>
                <div class="dropdown-item d-flex">
                    <div class="notification-icon">
                        <i class="i-Data-Power text-success mr-1"></i>
                    </div>
                    <div class="notification-details flex-grow-1">
                        <p class="m-0 d-flex align-items-center">
                            <span>Server Up!</span>
                            <span class="badge badge-pill badge-success ml-1 mr-1">3</span>
                            <span class="flex-grow-1"></span>
                            <span class="text-small text-muted ml-auto">14 hours ago</span>
                        </p>
                        <p class="text-small text-muted m-0">Server rebooted successfully</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Notificaiton End -->
        <!-- User avatar dropdown -->
        <div class="dropdown">
            <div class="user col align-self-end">
                <img src="{{ asset('assets/admin/images/faces/1.jpg') }}" id="userDropdown" alt="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <div class="dropdown-header">
                        <i class="i-Lock-User mr-1"></i> Timothy Carlson
                    </div>
                    <a class="dropdown-item">Account settings</a>
                    <a class="dropdown-item">Billing history</a>
                    <a href="{{ route('admin.logout') }}" class="dropdown-item" onclick="event.preventDefault();
                             document.getElementById('logout-form').submit();">{{ __('Sign out') }}
                
                  </a>

                <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
                    <!-- <a class="dropdown-item" href="signin.html">{{ __('Sign out') }}</a> -->
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/includes/script.blade.php
<script src="{{ asset('assets/admin/js/plugins/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('assets/admin/js/plugins/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/admin/js/plugins/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('assets/admin/js/scripts/script.min.js') }}"></script>
<script src="{{ asset('assets/admin/js/scripts/sidebar.large.script.min.js') }}"></script>
<script type="text/javascript">
	$.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>

resources/views/admin/includes/sidebar.blade.php
<div class="side-content-wrap">
    <div class="sidebar-left open rtl-ps-none" data-perfect-scrollbar="" data-suppress-scroll-x="true">
        <ul class="navigation-left">
            <li class="nav-item {{ request()->is('admin/dashboard') ? 'active' : ''}}"><a class="nav-item-hold" href="{{ route('admin.dashboard') }}"><i class="nav-icon i-Bar-Chart"></i><span class="nav-text">Dashboard</span></a>
                <div class="triangle"></div>
            </li>
            <li class="nav-item {{ request()->routeIs('admin.users*') ? 'active' : '' }}"><a class="nav-item-hold" href="{{ route('admin.users.index') }}"><i class="nav-icon i-Administrator"></i><span class="nav-text">Users</span></a>
                <div class="triangle"></div>
            </li>
            <li class="nav-item"><a class="nav-item-hold" href="{{ route('admin.plan.index') }}"><i class="nav-icon i-Money-2"></i><span class="nav-text">Pricing</span></a>
                <div class="triangle"></div>
            </li>
        </ul>
    </div>
    <div class="sidebar-overlay"></div>
</div>